[package]
name = "combinatorics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iterator_item = { git = "https://github.com/estebank/iterator_item.git" }
layout = { git = "https://github.com/nadavrot/layout.git" }

[[bin]]
name = "latin-squares"
path = "src/latin-squares.rs"

[[bin]]
name = "bdd"
path = "src/bdd.rs"

